customhost = "employee-portal.ckywzoplawl5.eu-west-2.rds.amazonaws.com"
customuser = "imran597769"
custompass = "imran597769"
customdb = "employee-portal"
custombucket = "employee-dd"
customregion = "eu-west-2c"
